### PR TITLE
Fixes #15325 - Handle nil params

### PR DESCRIPTION
**Pull request by akofink**
for 'capsule_certs' and 'parent_fqdn'

BATs are failing with `/usr/share/katello-installer-base/hooks/post/10-post_install.rb:22:in `block (4 levels) in load': undefined method `value' for nil:NilClass (NoMethodError)`

This was introduced in #332.

### CODE REVIEW

File: hooks/post/10-post_install.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def new_install?
 
 if [0,2].include?(@kafo.exit_code)
   if !app_value(:upgrade)
-    fqdn = @kafo.param('capsule_certs','parent_fqdn').value || Facter.value(:fqdn)
+    fqdn = @kafo.param('capsule_certs','parent_fqdn').try(&:value) || Facter.value(:fqdn)
```
Comment (jlsherrill) [inline hooks/post/10-post_install.rb]: I think you might mean   `.try(:value)`

**Comment by jlsherrill** [comment]
ACK merging!
